### ISSUE TITLE
Overlap detection training fail using the AMI dataset

### ISSUE THREAD

**Issue by Tomaubier** [pyannote/pyannote-audio#383] opened 2020-05-20 15:39 UTC
Hello,
I run into an issue during the training phase of the [overlap_detection](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/overlap_detection) tutorial.
I'm using the AMI dataset dowloaded according to the [data_preparation](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/data_preparation)
directions. However when I run `pyannote-audio ovl train --subset=train --to=1000 --parallel=4 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset`, the following warning gets thrown:

> Training set: 118it [00:18,  6.39it/s]
>    Training:   0%|                                     | 0/1000 [00:00<?, ?epoch/s]
> /info/etu/slbm/s160448/miniconda3/lib/python3.7/site-packages/pyannote/audio/train/generator.py:111: UserWarning: Skipping malformed batch.
> 1:   0%|                                      | 0/675 [00:00<?, ?batch/s]
>    warnings.warn(msg)

At that point the execution freezes without giving any additional error messages.
I have to mention that the database doesn't seem to be corrupted as the [feature_extraction](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/feature_extraction) steps went seamlessly.

Any suggestion on what is going on would be greatly appreciated.
Thanks!

**Comment by hbredin** [comment] 2020-05-25 07:13
Marking this issue as `cannot_reproduce` because you did not provide enough information to reproduce it.

Please use the [provided bug template](https://github.com/pyannote/pyannote-audio/issues/new?assignees=&labels=&template=bug_report.md&title=) to provide all the necessary details.

**Comment by hbredin** [comment] 2020-09-04 13:17
Closing this stalled issue. Please re-open if needed.

**Closed by hbredin** 2020-09-04 13:17 UTC
Labels: cannot_reproduce
