### ISSUE TITLE
streamlit demo

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#273] opened 2020-01-16 14:57 UTC
In preparation of 2.0 release, we would like to have a demo online where people could upload an audio file and have pretrained models applied on it (similar to what is described in [this tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained))

I suggest we use [`streamlit`](https://streamlit.io) for designing the app and [`Heroku`](https://heroku.com) (or any other free webhosting service) for hosting.

**Caveats 1.** It is unlikely that we find a free GPU-equipped webhosting service. So we would need to only allow processing short audio excerpts (we could even crop it ourselves).

**Caveats 2.** We don't want people to think pyannote.audio is bad just because their data doesn't match AMI, ETAPE or DIHARD domains. Should we train a domain classifier to decide on which model to use?

**Comment by hbredin** [comment] 2020-01-20 15:21
Here is a first screenshot.  
Code is available [here](https://github.com/pyannote/pyannote-audio/blob/demo/demo/sad.py).  
Launching the demo is as easy as `streamlit run sad.py`.  
It uses our best domain-adversarial model trained on DIHARD.



<img width="952" alt="image" src="https://user-images.githubusercontent.com/1080837/72737567-1cab0e80-3ba0-11ea-8e8c-d6bb4914a2e0.png">

@MarvinLvn this might be of interest to you and [your voice type classifier](https://github.com/MarvinLvn/voice-type-classifier).  
@MarvinLvn @hadware Any idea where we could host this kind of app?

**Comment by hadware** [comment] 2020-01-20 19:51
Nice, really nice.

I guess if the CPU load isn't too high, a simple Digital Ocean droplet might suffice?

**Comment by hbredin** [comment] 2020-05-20 07:05
This nice hack allows to run a streamlit app on Google Colab (free GPU, yeah!)

https://gist.github.com/hbredin/eda89f7204bbb7d3eae0a81c84c287b2

**Comment by deeshantk** [comment] 2020-07-18 08:56
I have been trying this in google colab but It isn't working. No webpage is popping up. I think I am doing something wrong.

Can someone help me out, I want to get rttm from a wav file. 

Thanks

**Comment by hbredin** [comment] 2020-07-19 08:29
I've never used this hack myself. But I think no webpage is supposed to pop-up.

You'd have to open a new tab in your browser yourself using the http://xxxxxxxxx.ngrok.io URL reported [by cell [3]](https://gist.github.com/hbredin/eda89f7204bbb7d3eae0a81c84c287b2).

**Comment by deeshantk** [comment] 2020-07-21 08:29
hey @hbredin,
I am using pyannote-audio pipeline for speaker diarization. I want timings of speaker change and also overlapped speech. This tutorial here seems perfect -> (https://colab.research.google.com/github/pyannote/pyannote-audio/blob/develop/notebooks/introduction_to_pyannote_audio_speaker_diarization_toolkit.ipynb#scrollTo=nxNf1l8Ye_U9).

While using same on my own audio file its correct (like the image). i have more than 4 speaker in the audio also overlapping speaker is not estimated. 
I guess I need to have a "rttm" file for that.
Can you help me on that?

Thanks
![Screen Shot 2020-07-21 at 1 58 25 PM](https://user-images.githubusercontent.com/44977226/88031575-67f7a700-cb5a-11ea-9ff2-a7c61c7d8125.png)

**Comment by hbredin** [comment] 2020-07-21 10:11
@deeshantk Please open a new issue as this has nothing to do with the original topic of this issue. 
Hiding your comment (and this one).

**Comment by mogwai** [comment] 2020-11-09 13:29
Duplicate of #474

**Comment by hbredin** [comment] 2021-02-02 09:38
Another hack to run streamlit app on Google Colab:

```python
!pip install streamlit

%%writefile app.py
import streamlit as st
st.write('Hello World')

!streamlit run app.py & npx localtunnel --port 8501
```

**Closed** 2021-07-28 13:36 UTC
Labels: v2
