### ISSUE TITLE
中文能力不咋地啊

### ISSUE THREAD

**Issue by xxm1668** [pyannote/pyannote-audio#1604] opened 2024-01-02 09:15 UTC

**Comment by luohao123** [comment] 2024-01-10 03:29
Dude, if you using FunASR, it could be worser....

**Comment by sanbaispeaking** [comment] 2024-01-21 06:55
家庭教养不咋地啊

**Comment by hbredin** [comment] 2024-02-11 07:34
Closing as duplicate of #1625

**Closed by hbredin** 2024-02-11 07:34 UTC
Labels: cannot_reproduce
