### ISSUE TITLE
ValueError: parameter 'segmentation_onset' does not exist

### ISSUE THREAD

**Issue by Ichraknaceur** [pyannote/pyannote-audio#1106] opened 2022-10-17 14:07 UTC
i got this error when running this code  : 

from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization')

any help please ? 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_15424/963617425.py in <cell line: 1>()
----> 1 pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization')

/usr/local/lib/python3.8/dist-packages/pyannote/audio/core/pipeline.py in from_pretrained(cls, checkpoint_path, hparams_file, use_auth_token, cache_dir)
    104 
    105         if "params" in config:
--> 106             pipeline.instantiate(config["params"])
    107 
    108         if hparams_file is not None:

/usr/local/lib/python3.8/dist-packages/pyannote/pipeline/pipeline.py in instantiate(self, params)
    442 
    443             msg = f"parameter '{name}' does not exist"
--> 444             raise ValueError(msg)
    445 
    446         self.initialize()

ValueError: parameter 'segmentation_onset' does not exist

**Comment by hbredin** [comment] 2022-10-18 08:57
Closing as duplicate of https://github.com/pyannote/pyannote-audio/issues/1100

**Closed by hbredin** 2022-10-18 08:57 UTC
