### ISSUE TITLE
Send to model single audio channel

### ISSUE THREAD

**Issue by Vintic** [pyannote/pyannote-audio#447] opened 2020-09-21 12:50 UTC
**Is your feature request related to a problem? Please describe.**
Why I should split my audio file to different channels, save them to tmp files and then read them from disk.

**Describe the solution you'd like**
Send audio object to model, not file path.

**Additional context**
My audio files are call recordings and contains to channels. 1st channel - client side, 2nd channel - company side.

**Comment by hbredin** [comment] 2020-09-23 12:56
Closing as duplicate of #431

**Closed by hbredin** 2020-09-23 12:56 UTC
