### ISSUE TITLE
Sadly onnxruntime-gpu dependency kills Mac support

### ISSUE THREAD

**Issue by dr-duplo** [pyannote/pyannote-audio#1505] opened 2023-10-19 07:26 UTC
Hi, thanks for the great package. Sadly the recently (3.0.1) introduced `onnxruntime-gpu` dependency kills Mac support. At least on M2 (didn't try anything else).

**Describe the solution you'd like**
- platform depended requirements? ([onnxruntime-silicon](https://github.com/cansik/onnxruntime-silicon ?)
- go back to `onnxruntime`?

**Comment by hbredin** [comment] 2023-10-19 07:27
Can you please clarify what you mean by "kills Mac support"?
I actually happen to develop `pyannote` on a Mac...

**Comment by dr-duplo** [comment] 2023-10-19 07:40
I wasn't able to install `pyannote.audio` due to a missing install candidate for `onnxruntime-gpu`. I'm on a M2.

**Comment by hbredin** [comment] 2023-10-19 14:00
Unfortunately I don't own an M2 mac myself (M1, it is).
To pyannote M2 users out there, could anyone help @dr-duplo with that?

**Comment by guilhermehge** [comment] 2023-10-20 20:00
You can just use a previous version of pyannote.audio. Find a commit before 3.0.1 and install it.

**Comment by reubinoff** [comment] 2023-10-22 11:39
I have mac with intel chipset and same for me. I cannot install version 3.0.1 only 3.0.0

**Comment by guilhermehge** [comment] 2023-10-23 00:41
This is simply because onnxruntime-gpu does not have [mac support](https://github.com/microsoft/onnxruntime/issues/12252).

**Comment by chrisbrickhouse** [comment] 2023-10-24 20:22
I reproduced the issue in our CI pipeline, you can see [the build failure](https://github.com/Forced-Alignment-and-Vowel-Extraction/fave-asr/actions/runs/6605549030/job/17940821838) on macos-latest caused by pyannote.
```
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu>=1.16.0 (from pyannote-audio) (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu>=1.16.0
```

> You can just use a previous version of pyannote.audio. Find a commit before 3.0.1 and install it.

While this is a viable workaround, it shouldn't be the solution. Breaking compatibility with an entire operating system shouldn't be introduced with a patch bump, and the loss of interoperability between 3.0.0 and 3.0.1 should be considered a bug.

The OP's suggestion of platform dependent requirements seems like a good middle path between backwards compatibility and fixing the bug which required the new dependency.

**Comment by justinwlin** [comment] 2023-10-25 00:19
Agree with @chrisbrickhouse does not make sense that a x.0.1 change would cause a broken OS compatibility. A fix forward for x.0.2 would be great to not require work-arounds.

**Comment by hbredin** [comment] 2023-10-25 07:11
Thanks for the feedback. 

Would any of you be willing to contribute to the project by opening a PR solving this issue?

**Comment by dr-duplo** [comment] 2023-10-25 07:18
> Thanks for the feedback.
> 
> Would any of you be willing to contribute to the project by opening a PR solving this issue?

I can do, but may need help to test it on other machines.

**Comment by hbredin** [comment] 2023-11-16 19:47
Closing as latest version no longer relies on ONNX runtime. 
Please update to [`pyannote.audio 3.1`](https://github.com/pyannote/pyannote-audio/releases/tag/3.1.0) and [`pyannote/speaker-diarization-3.1`](https://hf.co/pyannote/speaker-diarization-3.1) (and open new issues if needed).

**Closed by hbredin** 2023-11-16 19:47 UTC
Labels: help wanted
