### ISSUE TITLE
Questions about the frequent segmentation

### ISSUE THREAD

**Issue by ORainn** [pyannote/pyannote-audio#810] opened 2021-11-18 15:14 UTC
Hi there, I'm using your codes to process a wav file. In the results, I found that when the same speaker speaks continuously, his words will be divided into several paragraphs, like the following:

The link of this repo is [StreamingSpeakerDiarization](https://github.com/juanmc2005/StreamingSpeakerDiarization/)

SPEAKER output 1 4.953 1.249 <NA> <NA> speaker0 <NA> <NA> 
SPEAKER output 1 6.455 1.342 <NA> <NA> speaker0 <NA> <NA> 
SPEAKER output 1 8.691 0.253 <NA> <NA> speaker0 <NA> <NA>

Such frequent segmentation makes my subsequent speech recognition more difficult. So my question is, is it possible to speak without segmentation when the same speaker is speaking? Or is there any other way to achieve this effect?

Thank you.

**Comment by hbredin** [comment] 2021-11-18 15:28
Duplicate of https://github.com/juanmc2005/StreamingSpeakerDiarization/issues/11

**Closed by hbredin** 2021-11-18 15:28 UTC
