### ISSUE TITLE
How to train model use multi gpus?

### ISSUE THREAD

**Issue by Naminwang** [pyannote/pyannote-audio#340] opened 2020-04-02 12:16 UTC

**Comment by hbredin** [comment] 2020-04-02 12:18
Not supported yet. Solving [this issue](https://github.com/pyannote/pyannote-audio/issues/227) would make it happen. Wanna help?

**Comment by Naminwang** [comment] 2020-04-03 07:32
I found that when I run "pyannote-audio sad train --gpu" script, the script never use the gpu resources. I don't know what I missed.

**Comment by hbredin** [comment] 2020-04-03 07:54
Make sure you are using an up-to-date version of `develop` branch.
A speed regression in the batch generator [has been fixed on March 30th](b98a797c8f1a8722de2e8fc65943ffe56d3d7b64), that might explain this behavior.

**Comment by Naminwang** [comment] 2020-04-16 09:25
I changed some codes in applications\base.py and tasks\base.py, and now I can use multi-gpus to train model.
The changed detail：

1. In **applications\base.py** after `model = self.get_model_from_specs_(batch_generator.specifications)` add:
```
if torch.cuda.device_count() > 1:
    model = torch.nn.DataParallel(model)
    model.module.freeze(getattr(self, "freeze_", []))
else:
    model.freeze(getattr(self, "freeze_", []))
```
2. In  **tasks\base.py** changed `self.task_ = self.model_.task` to: 
```
if torch.cuda.device_count() > 1:
    self.task_ = self.model_.module.task
else:
    self.task_ = self.model_.task
```
3. In  **tasks\base.py** changed `self.n_classes_ = len(self.model_.classes)` to: 
```
if torch.cuda.device_count() > 1:
    self.n_classes_ = len(self.model_.module.classes)
else:
    self.n_classes_ = len(self.model_.classes)
```

**Comment by hbredin** [comment] 2020-04-16 11:36
That looks great, thanks!

I am new to `DataParallel` so bear with me if my questions are obious.
* How much faster is the training with, say, 2 GPUs? 
* Do your modifications allow for training with batch sizes that do not fit on one GPU?

Would you be interested in contributing this via a pull request? 
The whole `model.module` thing seems a bit hackish and will probably bite us later. There seems to be an elegant solution to that problem in paragraph "Attributes of the wrapped module" of the [Multi-GPU Examples](https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html) tutorial.

**Comment by Naminwang** [comment] 2020-04-17 00:29
@hbredin 

- If we use 1 GPU, we set the batch size 32, and it will has 100 iters. When we use DataParallel with 2 GPUs, we set the batch size 64, and it will has 50 iters behand the same dataset. So the training time 2 gpus is just half of the single gpu's. 

- I wonder if i had undanstood this question. After the modifacation, we also can use one GPU train the model, but the batch sizes should be adjusted to avoid GPU out of memory.

- Once i changed the codes without model.module just like the  Multi-GPU Examples tutorial, there were a lot of codes need to changed. At this situation, one of the gpus' Memory-Usage was high, and the others were same. Based that, I use model.module way, and all the gpus' Memory-Usage were same, we can use all the gpus memory maximum.

**Comment by Naminwang** [comment] 2020-04-24 00:30
Update this comment: https://github.com/pyannote/pyannote-audio/issues/340#issuecomment-614528263

- After a series experiments, I found that the loss of multi-gpus decrease slower than one gpu.

- When training use multi-gpus, the gpu util perform not very well. A lot of time was 0% to wait batch datas and gather multi gpus results.

- Need more time to change the codes adapt to multi-gpus.

**Comment by hbredin** [comment] 2020-04-24 10:47
Thanks for the update. To be continued, then :-)

**Comment by hbredin** [comment] 2020-09-04 13:22
Closing as this will eventually be taken care of in #227

**Closed by hbredin** 2020-09-04 13:22 UTC
