### ISSUE TITLE
Algorithm acceleration

### ISSUE THREAD

**Issue by pengyuan101** [pyannote/pyannote-audio#894] opened 2022-02-17 06:55 UTC
Thanks for your work.It really helps me a lot .But I have found that the most time of speaker_diarization is spent on speaker_embeding.Can you give me some suggestions for Algorithm acceleration?
thanks a lot!!!

**Comment by hbredin** [comment] 2022-02-17 10:35
Closing as duplicate of https://github.com/pyannote/pyannote-audio/discussions/852

**Closed** 2022-02-17 13:48 UTC
