### ISSUE TITLE
Reproducing results of "pyannote.audio" and "overlap-aware diarization" papers

### ISSUE THREAD

**Issue by yat011** [pyannote/pyannote-audio#263] opened 2019-12-29 08:43 UTC
Hi,

May I know how to reproduce the AMI diarization result in the paper "PYANNOTE.AUDIO: NEURAL BUILDING BLOCKS FOR SPEAKER DIARIZATION".  (i.e. DER = 29.6 in Table 5)

I followed the tutorial in https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pipelines/speaker_diarization, and the DER on AMI is 33.47.
(using the pretrained weights)

It would be great if there is a procedure to reproduce the result in the latest paper for comparison. (i.e. DER = 29.6)

Thanks a lot for your help in advance.

**Comment by hbredin** [comment] 2020-01-06 13:34
Numbers in Table 5 (e.g. DER = 29.6% for AMI) are based on `waveform` models from Tables 1 and 2, while numbers in the tutorial  (e.g. DER = 33.5% for AMI) are based on `MFCC` models. This explains the discrepancy. 

I am currently preparing the release of pyannote.audio 2.0 that includes pretrained `waveform` models (and associated configuration files). They are already [available](https://github.com/pyannote/pyannote-audio/tree/v2/models) in [branch v2](https://github.com/pyannote/pyannote-audio/tree/v2) of this repository. 

Note however that `pyannote-speech-detection`, `pyannote-change-detection` and other command line tools have been deprecated in favor of a unified `pyannote-audio` tool. The tutorials have not yet been updated accordingly so you might encounter some problems using them. My plan is to have everything ready and released [by beginning of May 2020](https://2020.ieeeicassp.org/).

**Comment by hbredin** [comment] 2020-01-06 13:54
The same applies for the overlapped speech detection results described in [Overlap-aware diarization: resegmentation using neural end-to-end overlapped speech detection](https://arxiv.org/abs/1910.11646). 

Numbers reported in Table 2 for both `MFCC` and `waveform` variants were obtained with configuration files that are different from the one used in the [current overlapped speech detection tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/overlap_detection).   

Here are the configuration file used for the [`MFCC`](https://gist.github.com/hbredin/eb09d9eccc3bd0388f2b7fd7bd25cf53) and [`waveform`](https://github.com/pyannote/pyannote-audio/blob/v2/models/ovl/ami/e86437107d/config.yml
) variants.

**Comment by yat011** [comment] 2020-01-07 13:20
Hi, thank you very much for the explanation and providing the config files and models! 
Now, I understand why they are different, and I will try to run them.

**Comment by hbredin** [comment] 2020-01-07 13:48
I'd be happy to hear back from you if/once you've succesfully reproduced our results.

**Comment by hbredin** [comment] 2020-01-21 13:01
Closing the issue. Please re-open if you couldn't reproduce the results.

**Closed by hbredin** 2020-01-21 13:01 UTC

**Comment by yat011** [comment] 2020-01-31 10:21
Hi,
I applied the pretrained SAD model in [https://github.com/pyannote/pyannote-audio/tree/develop/models/sad/ami/712d7e3184](https://github.com/pyannote/pyannote-audio/tree/develop/models/sad/ami/712d7e3184) on the AMI development set and test set.  
However, I got the results which are slighty different from params.yml and the paper.

For development, the detection error rate which I got is 5.69, but the detection_error_rate in the provided params.yml is 5.8
There are also differences in test set.

I attach the generated results for your reference.

[AMI.SpeakerDiarization.MixHeadset.test.eval.txt](https://github.com/pyannote/pyannote-audio/files/4138753/AMI.SpeakerDiarization.MixHeadset.test.eval.txt)
[AMI.SpeakerDiarization.MixHeadset.development.eval.txt](https://github.com/pyannote/pyannote-audio/files/4138754/AMI.SpeakerDiarization.MixHeadset.development.eval.txt)


Using setup:
pyannote-audio commit 62b8eee17eabd476e0ac4f3bf1b995ba6b2b87ee


Thanks a lot for your help in advance.
