### ISSUE TITLE
Missing Precomputed features for files in emb_ami 

### ISSUE THREAD

**Issue by monika-saroj** [pyannote/pyannote-audio#384] opened 2020-05-22 04:06 UTC
I am facing the below error while running the command :
pyannote-pipeline apply --subset=test ${TRN_DIR} AMI.SpeakerDiarization.MixHeadset

Traceback (most recent call last):
  File "/home/ubuntu/smonika/pyannote-audio/env37/bin/pyannote-pipeline", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/smonika/pyannote-audio/env37/lib/python3.7/site-packages/pyannote/pipeline/experiment.py", line 453, in main
    experiment.apply(protocol_name, output_dir, subset=subset)
  File "/home/ubuntu/smonika/pyannote-audio/env37/lib/python3.7/site-packages/pyannote/pipeline/experiment.py", line 364, in apply
    output = self.pipeline_(current_file)
  File "/home/ubuntu/smonika/pyannote-audio/env37/lib/python3.7/site-packages/pyannote/audio/pipeline/speaker_diarization.py", line 188, in __call__
    long_speech_turns = self.speech_turn_clustering(current_file, long_speech_turns)
  File "/home/ubuntu/smonika/pyannote-audio/env37/lib/python3.7/site-packages/pyannote/audio/pipeline/speech_turn_clustering.py", line 244, in __call__
    return self._turn_level(current_file, speech_turns)
  File "/home/ubuntu/smonika/pyannote-audio/env37/lib/python3.7/site-packages/pyannote/audio/pipeline/speech_turn_clustering.py", line 180, in _turn_level
    embedding = self._embedding(current_file)
  File "/home/ubuntu/smonika/pyannote-audio/env37/lib/python3.7/site-packages/pyannote/audio/features/wrapper.py", line 274, in __call__
    return self.scorer_(current_file)
  File "/home/ubuntu/smonika/pyannote-audio/env37/lib/python3.7/site-packages/pyannote/audio/features/precomputed.py", line 215, in __call__
    raise PyannoteFeatureExtractionError(msg)
pyannote.audio.features.precomputed.PyannoteFeatureExtractionError: Directory /home/ubuntu/smonika/pyannote-audio/tutorials/pipelines/speaker_diarization/emb_ami does not contain precomputed features for file "EN2002a.Mix-Headset" of "AMI" database.

I tried steps in the below link for feature extraction:
https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/feature_extraction
before performing training of the speaker diarization pipeline.
But i am still getting the above error while testing the pipeline.

Please guide me here.

**Comment by hbredin** [comment] 2020-05-25 07:11
Marking this issue as `cannot_reproduce` because you did not provide enough information to reproduce it.

Please use the [provided bug template](https://github.com/pyannote/pyannote-audio/issues/new?assignees=&labels=&template=bug_report.md&title=) to provide all the necessary details.

**Comment by hbredin** [comment] 2020-09-04 13:17
Closing. Please re-open if needed.

**Closed by hbredin** 2020-09-04 13:17 UTC
Labels: cannot_reproduce
