### ISSUE TITLE
Negative dimensions are not allowed while diarizing wav file

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [pyannote/pyannote-audio#1166] opened 2022-11-24 12:58 UTC
Hi,

I have a list of short wav files (Mono 16kHz) and I need to know if there is only a single speaker talking in each wav.

So I use the following code to do that :

```
pipeline = Pipeline.from_pretrained(
"pyannote/speaker-diarization@2.1",                         use_auth_token=ACCESS_TOKEN,
                                    )

diarization = pipeline(
            mono_16kHz_wav_file 
            )
```

It works great most of the time but sometimes it crashes due to :

```
   diarization = pipeline(
  File "/home/caraduf/whisperenv/lib/python3.10/site-packages/pyannote/audio/core/pipeline.py", line 238, in __call__
    return self.apply(file, **kwargs)
  File "/home/caraduf/whisperenv/lib/python3.10/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 512, in apply
    discrete_diarization = self.reconstruct(
  File "/home/caraduf/whisperenv/lib/python3.10/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 397, in reconstruct
    clustered_segmentations = np.NAN * np.zeros(
ValueError: negative dimensions are not allowed
```

The waveform looks like this if it matters : 

![Diarization_Waveform](https://user-images.githubusercontent.com/91517923/203789643-9a4d2375-915e-401f-94a5-b952d27dd67b.png)

Why is it failing to process that audio, I don't understand where the negative dimensions come from ?

Thanks in advance for helping :)

**Comment by hbredin** [comment] 2022-11-25 12:54
To maximise the probability of someone answering your question:

* if your issue is a bug report, please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. a link to a self-contained [Google Colab](https://colab.research.google.com/) notebook (i.e. containing everthing needed to reproduce the bug: installation of pyannote.audio, downloads of models or test data, etc...)

* if your issue is a feature request, please [read this](https://xyproblem.info/) first and update your request accordingly.

**Comment by Jeronymous** [comment] 2022-12-15 08:33
It is a corner case, that I noticed when making an example for [#1196](https://github.com/pyannote/pyannote-audio/issues/1196).

Here is a minimum reproducible example:
```
from pyannote.audio import Pipeline
import soundfile as sf
import tempfile
import numpy as np

pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1", use_auth_token = "hf_XXX") # USE YOUR HUGGINGFACE TOKEN HERE

data = np.zeros((16000,))
with tempfile.NamedTemporaryFile(suffix=".wav") as f:
    sf.write(f.name, data, 16000)
    pipeline(f.name, num_speakers = 2)
```
It also happens most of the time with a random signal `data = np.random.uniform(-1, 1, size=(2 * 16000,))`

The problem is that `num_clusters` can be -1 in the method`SpeakerDiarization.reconstruct()` when there is no detected speaker.

**Comment by hbredin** [comment] 2022-12-15 11:34
Thanks @Jeronymous for narrowing things down. I pushed a fix. It will be part of next release.

**Closed** 2022-12-15 11:34 UTC

**Comment by Ca-ressemble-a-du-fake** [comment] 2022-12-15 14:39
Great that you could fix it! Thanks to both of you!
