### ISSUE TITLE
VAD training very slow for Toy Problem

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#253] opened 2019-12-17 03:12 UTC
I am trying to train the VAD module on my own data. For starters, I only have one annotated utterance of about 10 minutes total duration. I cut down the number of nodes to [4,4] before labeling by hand more data to train the VAD component. I managed to get things running but training seems extremely slow - roughly speaking, 2 seconds or so a batch and it is processing ~600 batches. Does this make any sense? I tried profiling the code and it looks like the batch generation and data loading is what is taking the bulk of the time. I can load a .prof file if anyone would be interesting in giving me a hand with this to verify that is the root of the problem (and also to suggest a solution!!!!)

**Comment by hbredin** [comment] 2019-12-17 08:14
> I am trying to train the VAD module on my own data. For starters, I only have one annotated utterance of about 10 minutes total duration. I cut down the number of nodes to [4,4] before labeling by hand more data to train the VAD component. 

I am not sure what the term _"nodes"_ refers to. Can you please clarify? 

> I managed to get things running but training seems extremely slow - roughly speaking, 2 seconds or so a batch and it is processing ~600 batches. Does this make any sense? 

Can you please share your configuration file? 

If you are using the configuration file from [this tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speech_activity_detection), `per_epoch: 1` means that one epoch is one full day of audio. This explains the 675 batches per epoch (24 hours x 60 minutes x 60 seconds) / (2 seconds/chunk x 64 chunks/batch). 

Regarding the slowness of each batch, this should be faster after the first epoch because the batch generator does some prefetching in the background. Features cannot be precomputed because of on-the-fly data augmentation.

**Comment by picheny-nyu** [comment] 2019-12-17 13:18
First, thank you very much for your quick reply!! I really appreciate it and your help!!!!

By nodes, I mean the number of LSTM units per layer.

I did not realize the data was being expanded from 10 minutes to 24 hours. Is there some way to cut this down for the sake of debugging? Or do you not recommend it? At most, I will hand label 1 hour of speech (it is rather tedious and I have to do this myself). In such a case what is the recommended configuration?

Lastly, even with 24 hours of speech the training seems a bit slow - about 2 seconds/batch x675 batches ~ 20 minutes/epoch, with a tiny network. Was just wondering what you are seeing on your systems? I have to check what GPU I am running on (I use some heterogenous batch management system so I could have been running on a slow GPU).

**Comment by hbredin** [comment] 2019-12-17 13:50
> I did not realize the data was being expanded from 10 minutes to 24 hours. Is there some way to cut this down for the sake of debugging? Or do you not recommend it? At most, I will hand label 1 hour of speech (it is rather tedious and I have to do this myself). In such a case what is the recommended configuration?

Just change `per_epoch` to the actual duration (in days) of your dataset.
For 10 minutes, it would be 10 minutes / (24 hours x 60 minutes) = 0.007
`per_epoch: 0.007`
> 
> Lastly, even with 24 hours of speech the training seems a bit slow - about 2 seconds/batch x675 batches ~ 20 minutes/epoch, with a tiny network. Was just wondering what you are seeing on your systems? I have to check what GPU I am running on (I use some heterogenous batch management system so I could have been running on a slow GPU).

It might be related to #252 where you told me that you are using 8 Khz but extracting features assuming 16 Khz. It implies that audio chunks are upsampled on-the-fly, hence making the whole batch generation process very slow.

**Comment by picheny-nyu** [comment] 2019-12-17 14:24
Thanks again! 

Unfortunately not; I did set the sampling rate to 8000 (Or think I did....):

feature_extraction:
   name: LibrosaMFCC      # use MFCC from librosa
   params:
      e: False            # do not use energy
      De: True            # use energy 1st derivative
      DDe: True           # use energy 2nd derivative
      coefs: 19           # use 19 MFCC coefficients
      D: True             # use coefficients 1st derivative
      DD: True            # use coefficients 2nd derivative
      duration: 0.025     # extract MFCC from 25ms windows
      step: 0.010         # extract MFCC every 10ms
      sample_rate: 8000  # convert to 16KHz first (if needed)

**Comment by picheny-nyu** [comment] 2019-12-17 18:43
I have tried to profile the code (I am not sure I know what I am doing, honestly) and it looks as if most of the time is going into background.py in the "next" function. Does this make any sense?

**Comment by hbredin** [comment] 2020-01-06 13:21
Sorry for the delay in coming back to you. 

It has been a while since I last trained a model using MFCC feature extraction.
Nowadays, I tend to recommend training end-to-end model: see [pyannote.audio introductory paper](https://arxiv.org/pdf/1911.01255.pdf) (submitted to ICASSP 2020).
I suspect MFCC feature extraction is the bottleneck, here.

Could you try and adapt [this configuration file](https://github.com/pyannote/pyannote-audio/blob/v2/models/sad/ami/d534ec1eb2/config.yml)? 

Note that I am currently working on preparing the release of pyannote.audio 2.0 that includes a major improvement in terms of computation time. This is already available in branch [v2](https://github.com/pyannote/pyannote-audio/tree/v2) but the tutorials have not yet been updated.

**Comment by hbredin** [comment] 2020-01-16 13:29
I just pushed the (aforementioned) major update to pyannote.audio in `develop` branch.

The batch generation process has been greatly optimized and this should solve your issue. Can you please try again by updating to the latest version available in `develop` branch and following the (updated) tutorials again? 

In particular, there is now a `--parallel=N` option that makes the batch generator use (at most) that many background threads. You might not notice a big difference for the first few batches but  you will eventually, once the batch generator reaches its cruising speed (it automagically adapts the number of threads after a little while). I'd be happy to hear feedback about it.

**Comment by hbredin** [comment] 2020-01-21 14:59
Closing as (near) duplicate of (solved) issue #271.
Please re-open if needed.

**Closed by hbredin** 2020-01-21 14:59 UTC

**Comment by picheny-nyu** [comment] 2020-01-21 15:06
Thank you. As it turns out my problem was downsampling of the noise files as I am running things at 8 KHz. That is where most of the time was going! When I downsampled the noise files in advance, I saw a dramatic speedup!!!

Thanks
Michael
