### ISSUE TITLE
Problem when installing pyannote-audio

### ISSUE THREAD

**Issue by vadimkantorov** [pyannote/pyannote-audio#441] opened 2020-09-15 10:33 UTC
Note the huge number of dependencies pyannote-audio requires :( I managed to work around by doing some installs with `--no-dependencies` and then manually installing missing packages.

llvmlite fails to install for now

```
Processing /root/convasr/pyannote-audio
Requirement already satisfied: cachetools>=2.0.0 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (4.1.1)
Processing /root/.cache/pip/wheels/11/f0/b0/a8f9944f274bbc0f0159f2268f43dadcfa1cfe50a9007d8e1f/librosa-0.7.2-py3-none-any.whl
Collecting numba==0.48.0
  Using cached numba-0.48.0-1-cp38-cp38-manylinux2014_x86_64.whl (3.6 MB)
Requirement already satisfied: pandas>=0.18.0 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (1.1.0)
Requirement already satisfied: pyannote.core>=4.1 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (4.1)
Collecting pyannote.database>=4.0
  Using cached pyannote.database-4.0.1-py3-none-any.whl (41 kB)
Collecting pyannote.metrics>=2.3
  Using cached pyannote.metrics-3.0.1-py3-none-any.whl (49 kB)
Collecting pyannote.pipeline>=1.5
  Using cached pyannote.pipeline-1.5.2-py3-none-any.whl (25 kB)
Requirement already satisfied: pyYAML>=3.12 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (5.3.1)
Requirement already satisfied: scikit-learn>=0.20.2 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (0.23.2)
Collecting sortedcollections>=1.0.1
  Using cached sortedcollections-1.2.1-py2.py3-none-any.whl (8.4 kB)
Requirement already satisfied: sortedcontainers>=2.0.4 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (2.2.2)
Requirement already satisfied: soundfile>=0.10.2 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (0.10.3.post1)
Requirement already satisfied: tqdm>=4.29.1 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (4.46.0)
Requirement already satisfied: tensorboard>=2.0.0 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (2.3.0)
Processing /root/.cache/pip/wheels/04/04/bb/78c0daaafa679c767a2c5be25e36390f33ffecad7aee7ad10e/pescador-2.1.0-py3-none-any.whl
Requirement already satisfied: Pillow>=6.2.1 in /miniconda/lib/python3.8/site-packages (from pyannote.audio==2.0a1+63.g4d7687d) (7.2.0)
Requirement already satisfied: resampy>=0.2.2 in /miniconda/lib/python3.8/site-packages (from librosa==0.7.2->pyannote.audio==2.0a1+63.g4d7687d) (0.2.2)
Requirement already satisfied: joblib>=0.12 in /miniconda/lib/python3.8/site-packages (from librosa==0.7.2->pyannote.audio==2.0a1+63.g4d7687d) (0.16.0)
Requirement already satisfied: numpy>=1.15.0 in /miniconda/lib/python3.8/site-packages (from librosa==0.7.2->pyannote.audio==2.0a1+63.g4d7687d) (1.19.1)
Requirement already satisfied: scipy>=1.0.0 in /miniconda/lib/python3.8/site-packages (from librosa==0.7.2->pyannote.audio==2.0a1+63.g4d7687d) (1.5.0)
Requirement already satisfied: audioread>=2.0.0 in /miniconda/lib/python3.8/site-packages (from librosa==0.7.2->pyannote.audio==2.0a1+63.g4d7687d) (2.1.8)
Requirement already satisfied: six>=1.3 in /miniconda/lib/python3.8/site-packages (from librosa==0.7.2->pyannote.audio==2.0a1+63.g4d7687d) (1.15.0)
Requirement already satisfied: decorator>=3.0.0 in /miniconda/lib/python3.8/site-packages (from librosa==0.7.2->pyannote.audio==2.0a1+63.g4d7687d) (4.4.2)
Requirement already satisfied: setuptools in /miniconda/lib/python3.8/site-packages (from numba==0.48.0->pyannote.audio==2.0a1+63.g4d7687d) (49.2.0.post20200714)
Collecting llvmlite<0.32.0,>=0.31.0dev0
  Using cached llvmlite-0.31.0-cp38-cp38-manylinux1_x86_64.whl (20.2 MB)
Requirement already satisfied: pytz>=2017.2 in /miniconda/lib/python3.8/site-packages (from pandas>=0.18.0->pyannote.audio==2.0a1+63.g4d7687d) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /miniconda/lib/python3.8/site-packages (from pandas>=0.18.0->pyannote.audio==2.0a1+63.g4d7687d) (2.8.1)
Requirement already satisfied: matplotlib>=2.0.0 in /miniconda/lib/python3.8/site-packages (from pyannote.core>=4.1->pyannote.audio==2.0a1+63.g4d7687d) (3.3.0)
Requirement already satisfied: simplejson>=3.8.1 in /miniconda/lib/python3.8/site-packages (from pyannote.core>=4.1->pyannote.audio==2.0a1+63.g4d7687d) (3.17.2)
Requirement already satisfied: typing-extensions>=3.7.4.1 in /miniconda/lib/python3.8/site-packages (from pyannote.core>=4.1->pyannote.audio==2.0a1+63.g4d7687d) (3.7.4.3)
Collecting typer[all]>=0.2.1
  Using cached typer-0.3.2-py3-none-any.whl (21 kB)
Processing /root/.cache/pip/wheels/56/ea/58/ead137b087d9e326852a851351d1debf4ada529b6ac0ec4e8c/docopt-0.6.2-py2.py3-none-any.whl
Collecting sympy>=1.1
  Using cached sympy-1.6.2-py3-none-any.whl (5.8 MB)
Collecting tabulate>=0.7.7
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Processing /root/.cache/pip/wheels/d8/a5/4a/10760cc2469a33c24c5cec2008c1fc763c44aa8739ae1fda13/optuna-2.1.0-py3-none-any.whl
Collecting filelock>=3.0.10
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Requirement already satisfied: threadpoolctl>=2.0.0 in /miniconda/lib/python3.8/site-packages (from scikit-learn>=0.20.2->pyannote.audio==2.0a1+63.g4d7687d) (2.1.0)
Requirement already satisfied: cffi>=1.0 in /miniconda/lib/python3.8/site-packages (from soundfile>=0.10.2->pyannote.audio==2.0a1+63.g4d7687d) (1.14.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (1.7.0)
Requirement already satisfied: protobuf>=3.6.0 in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (3.12.4)
Requirement already satisfied: markdown>=2.6.8 in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (3.2.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (0.4.1)
Requirement already satisfied: grpcio>=1.24.3 in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (1.30.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (0.34.2)
Requirement already satisfied: werkzeug>=0.11.15 in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (1.0.1)
Requirement already satisfied: absl-py>=0.4 in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (0.9.0)
Requirement already satisfied: requests<3,>=2.21.0 in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (2.23.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in /miniconda/lib/python3.8/site-packages (from tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (1.20.0)
Collecting pyzmq>=15.0
  Using cached pyzmq-19.0.2-cp38-cp38-manylinux1_x86_64.whl (1.1 MB)
Requirement already satisfied: cycler>=0.10 in /miniconda/lib/python3.8/site-packages (from matplotlib>=2.0.0->pyannote.core>=4.1->pyannote.audio==2.0a1+63.g4d7687d) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /miniconda/lib/python3.8/site-packages (from matplotlib>=2.0.0->pyannote.core>=4.1->pyannote.audio==2.0a1+63.g4d7687d) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /miniconda/lib/python3.8/site-packages (from matplotlib>=2.0.0->pyannote.core>=4.1->pyannote.audio==2.0a1+63.g4d7687d) (1.2.0)
Collecting click<7.2.0,>=7.1.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Requirement already satisfied: colorama<0.5.0,>=0.4.3; extra == "all" in /miniconda/lib/python3.8/site-packages (from typer[all]>=0.2.1->pyannote.database>=4.0->pyannote.audio==2.0a1+63.g4d7687d) (0.4.3)
Collecting shellingham<2.0.0,>=1.3.0; extra == "all"
  Using cached shellingham-1.3.2-py2.py3-none-any.whl (11 kB)
Processing /root/.cache/pip/wheels/29/2c/1c/d2e4580cde2743b0aef389e936ac21a2db92921ddbca53faa1/mpmath-1.1.0-py3-none-any.whl
Requirement already satisfied: packaging>=20.0 in /miniconda/lib/python3.8/site-packages (from optuna>=1.4->pyannote.pipeline>=1.5->pyannote.audio==2.0a1+63.g4d7687d) (20.4)
Collecting sqlalchemy>=1.1.0
  Using cached SQLAlchemy-1.3.19-cp38-cp38-manylinux2010_x86_64.whl (1.3 MB)
Collecting alembic
  Using cached alembic-1.4.3-py2.py3-none-any.whl (159 kB)
Collecting colorlog
  Using cached colorlog-4.2.1-py2.py3-none-any.whl (14 kB)
Collecting cliff
  Using cached cliff-3.4.0-py3-none-any.whl (76 kB)
Collecting cmaes>=0.6.0
  Using cached cmaes-0.6.1-py3-none-any.whl (9.7 kB)
Requirement already satisfied: pycparser in /miniconda/lib/python3.8/site-packages (from cffi>=1.0->soundfile>=0.10.2->pyannote.audio==2.0a1+63.g4d7687d) (2.20)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /miniconda/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (1.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /miniconda/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /miniconda/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /miniconda/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /miniconda/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (1.25.10)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /miniconda/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.5" in /miniconda/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (4.6)
Collecting python-editor>=0.3
  Using cached python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting Mako
  Using cached Mako-1.1.3-py2.py3-none-any.whl (75 kB)
Processing /root/.cache/pip/wheels/46/60/6c/bb25d05df22906786206e901e9354bb3061061191116768bee/prettytable-0.7.2-py3-none-any.whl
Collecting pbr!=2.1.0,>=2.0.0
  Using cached pbr-5.5.0-py2.py3-none-any.whl (106 kB)
Collecting cmd2!=0.8.3,>=0.8.0
  Using cached cmd2-1.3.9-py3-none-any.whl (131 kB)
Collecting stevedore>=2.0.1
  Using cached stevedore-3.2.2-py3-none-any.whl (42 kB)
Requirement already satisfied: oauthlib>=3.0.0 in /miniconda/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (3.1.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /miniconda/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard>=2.0.0->pyannote.audio==2.0a1+63.g4d7687d) (0.4.8)
Requirement already satisfied: MarkupSafe>=0.9.2 in /miniconda/lib/python3.8/site-packages (from Mako->alembic->optuna>=1.4->pyannote.pipeline>=1.5->pyannote.audio==2.0a1+63.g4d7687d) (1.1.1)
Requirement already satisfied: wcwidth>=0.1.7 in /miniconda/lib/python3.8/site-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna>=1.4->pyannote.pipeline>=1.5->pyannote.audio==2.0a1+63.g4d7687d) (0.2.5)
Requirement already satisfied: attrs>=16.3.0 in /miniconda/lib/python3.8/site-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna>=1.4->pyannote.pipeline>=1.5->pyannote.audio==2.0a1+63.g4d7687d) (19.3.0)
Processing /root/.cache/pip/wheels/03/79/58/ab51f0f590281b0f4f6046d9271eb98cc50565afb9200f155a/pyperclip-1.8.0-py3-none-any.whl
Building wheels for collected packages: pyannote.audio
  Building wheel for pyannote.audio (setup.py) ... done
  Created wheel for pyannote.audio: filename=pyannote.audio-2.0a1+63.g4d7687d-py3-none-any.whl size=230960 sha256=9ca944ea02dc5acdae2eb9794e705d3db0833bb62b99dd48cf97dfdff47e5b9a
  Stored in directory: /root/.cache/pip/wheels/90/3b/47/a6d86a4458a8cfa24549f5c39c0e6bf49592ccec68b6d9b747
Successfully built pyannote.audio
Installing collected packages: llvmlite, numba, librosa, click, shellingham, typer, pyannote.database, docopt, mpmath, sympy, tabulate, pyannote.metrics, sqlalchemy, python-editor, Mako, alembic, colorlog, PrettyTable, pbr, pyperclip, cmd2, stevedore, cliff, cmaes, optuna, filelock, pyannote.pipeline, sortedcollections, pyzmq, pescador, pyannote.audio
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.33.0+1.g022ab0f
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by hbredin** [comment] 2020-09-16 09:25
Thanks for your interested in pyannote. Closing as duplicate of #421

**Closed by hbredin** 2020-09-16 09:25 UTC

**Comment by vadimkantorov** [comment] 2020-09-16 09:41
These huge dependencies are due to pescador. Maybe pescador is overkill for batching over an audio

**Comment by hbredin** [comment] 2020-09-16 10:37
I am in the process of refactoring the whole codebase to use pytorch-lightning and DistributedDataLoader: side effect is to get rid of pescador.  

See [this draft PR](https://github.com/pyannote/pyannote-audio/pull/407). Would you like to help?
