### ISSUE TITLE
Diarization using predefined number of speakers

### ISSUE THREAD

**Issue by bchinnari** [pyannote/pyannote-audio#699] opened 2021-07-05 13:34 UTC
In my speech recordings, I know the number of speakers before hand. Is it possible to specify the number of speakers when using pretrained pipeline to do diarization?

**Comment by hbredin** [comment] 2021-07-08 07:11
Short answer: no.
Long answer: https://github.com/pyannote/pyannote-audio/issues/573

Closing as duplicate of above-linked issue.

**Closed by hbredin** 2021-07-08 07:11 UTC
