### ISSUE TITLE
Can't install requeriments (pytorch error)

### ISSUE THREAD

**Issue by polazaro** [pyannote/pyannote-audio#201] opened 2019-07-22 18:51 UTC
I am trying to install the requeriments inside my conda enviroment and I obtain this error:

![image](https://user-images.githubusercontent.com/43273072/61657082-69319200-acc2-11e9-92c2-de99ad4a8164.png)

**Comment by hbredin** [comment] 2019-07-24 03:17
I cannot reproduce this error.

Did you follow the [installation instructions](https://github.com/pyannote/pyannote-audio#installation)?

**Comment by polazaro** [comment] 2019-07-24 06:54
Yes I did, step by step

**Comment by lizfischer** [comment] 2019-07-24 17:26
I'm also having this issue. Windows 10, Python 3.7.1, pip 19.2.1.

![image](https://user-images.githubusercontent.com/7800842/61814692-32689280-ae0e-11e9-9723-39f78b5d011c.png)

**Comment by hbredin** [comment] 2019-07-24 18:20
This might be an issue with `pytorch` not being available on PyPI for this combination of OS and Python version. Does `pip install torch` work?

@polazaro What is your OS and Python version? 

You might need to follow installation instructions available [here](https://pytorch.org/get-started/locally/)

**Comment by polazaro** [comment] 2019-07-24 18:24
I already fixed the problem. You have to install with conda statement before pip installing the requirements.

**Comment by hbredin** [comment] 2019-07-24 18:26
Hmmmm. So you did not follow the instructions in the first place, right?
I just want to make sure installation instructions work for everyone...

**Comment by polazaro** [comment] 2019-07-24 18:28
I just installed pytorch with conda after creating the environment and before pip installing everything

**Comment by hbredin** [comment] 2019-07-24 18:29
OK. Thanks. 

So, basically I need to add something like  `conda install pytorch -c pytorch` to the installation instructions, right?

**Comment by polazaro** [comment] 2019-07-25 00:51
Yes, in my case conda install worked for me.

**Comment by chuanliubuxi137** [comment] 2019-08-15 03:40
Hi, Does anyone run pyannote with Cycharm?
foward to answer

**Comment by hbredin** [comment] 2019-11-07 12:34
Closing this stalled issue. Please re-open if needed.

**Closed by hbredin** 2019-11-07 12:34 UTC
Labels: cannot_reproduce
