### ISSUE TITLE
Passing raw audio data instead of audio files to pretrained models

### ISSUE THREAD

**Issue by ajay960singh** [pyannote/pyannote-audio#576] opened 2021-01-16 05:33 UTC
Hey guys,

Is there a way to pass the raw audio data directly to pretained models?

Currently it seems like that the only input allowed are the audio files. We are extracting raw audio data using the `Sounddevice` library in Python and we want to pass the raw data directly. Our data looks like this for reference -

```
b'I\xff\xa2\xff\xf6\xffC\x00\xa8\x00\x16\x01r\x01\xc7\x01\x15\x029\x02E\x02\\\x02\x85\x02\xb8\x02\xe5\x02\x0e\x033\x03Q\x03h\x03h\x03S\x03C\x033\x03\x0c\x03\xd8\x02\xba\x02\x95\x02^\x02<\x02\x12\x02\xce\x01\x82\x01;\x01\xf0\x00\xa0\x00X\x00\t\x00\xbf\xff\x7f\xff?\xff\x0f\xff\xe1\xfe\xa4\xfex\xfeV\xfe(\xfe\x0e\xfe\t\xfe\x10\xfe\'\xfe9\xfe_\xfe\x84\xfe\x97\xfe\xc8\xfe\xe4\xfe\x01\xff-\xff^\xff\x8c\xff\xa5\xff\xdf\xff&\x00_\x00\x94\x00\xac\x00\xcc\x00\x10\x01X\x01\x8f\x01\xc8\x01\xf5\x01\x02\x02\x0c\x02\x14\x02\x05\x02\xee\x01\xcf\x01\xbc\x01\xb5\x01\x99\x01\x7f\x01f\x01F\x016\x01\'\x01\x0e\x01\xfa\x00\xdb\x00\xc3\x00\xcc\x00\xcf\x00\xb7\x00\x99\x00{\x00W\x00*\x00\xfa\xff\xcb\xff\x9e\xffr\xffW\xff<\xff&\xff)\xff)\xff\x1f\xff\x0c\xff\x03\xff\x07\xff\t\xff\n\xff\x0f\xff+\xffG\xffc\xffy\xff\x89\xff\x92\xff\x98\xff\xa1\xff\x8b\xffw\xffX\xff \xff\xe4\xfe\x87\xfe \xfe\xb7\xfd@\xfd\xdf\xfc\x90\xfc_\xfcA\xfc.\xfc%\xfc"\xfc:\xfcY\xfcn\xfc\x82\xfc\x9e\xfc\xca\xfc\x03\xfd\\\xfd\xc0\xfd\x1d\xfe}\xfe\xd7\xfe4\xff\x95\xff\xf0\xffI\x00\x9b\x00\xf3\x00J\x01\x93\x01\xd4\x01\x01\x02\x1f\x02C\x02g\x02\x8f\x02\xcb\x02\xfd\x02\x17\x039\x03b\x03\x84\x03\x95\x03\x99\x03\x8f\x03u\x03P\x03$\x03\xfe\x02\xcd\x02\x87\x02N\x02\x13\x02\xc5\x01|\x01-\x01\xd5\x00\x8b\x00F\x00\xff\xff\xc2\xff\x8a\xffP\xff.\xff\x16\xff\xef\xfe\xcd\xfe\xa8\xfe}\xfe\\\xfe=\xfe<\xfeC\xfeE\xfeL\xfeN\xfe^\xfee\xfez\xfe\xad\xfe\xd5\xfe\x11\xff\\\xff\xa5\xff\xe6\xff\x1d\x00d\x00\xa2\x00\xd5\x00\r\x01H\x01~\x01\xad\x01\xd7\x01\xec\x01\x0e\x02,\x02"\x02&\x02.\x02)\x02 \x02\x19\x02\r\x02\xf6\x01\xe4\x01\xcd\x01\xab\x01\x84\x01Z\x014\x01\x1b\x01\x0f\x01\t\x01\xf2\x00\xd6\x00\xb9\x00\x93\x00m\x00K\x00\x15\x00\xdb\xff\xb3\xff\x84\xffT\xff.
```

Thanks

**Comment by hbredin** [comment] 2021-01-16 14:49
Duplicate of #456 #431

**Closed by hbredin** 2021-01-16 14:49 UTC
