### ISSUE TITLE
Include support for reading audio file from io ByteIO

### ISSUE THREAD

**Issue by hyw2** [pyannote/pyannote-audio#955] opened 2022-04-20 21:11 UTC
**Is your feature request related to a problem? Please describe.**
Hi, my team is working on using the speech diarization within our processing pipeline and to optimize for speed, we are passing our audio files through a BytesIO object to keep the data in memory without having to read from disk. Currently, if we pass in a BytesIO from a wav file, pyannote is doing something to the io stream before passing it to soundfile to be read. To work around this, we added this if statement into pyannote.audio.features.utils.py in line 236: 

```{python}
if isinstance(current_file["audio"], io.BytesIO):
    current_file["audio"].seek(0)
```

Can this feature be added into a future release? Thank you!

Sample code to reproduce issue:

```{python}
import torch
import io

pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia')

with open("test_file.wav", "rb") as file:
     stream = io.BytesIO(file.read())

diarization = pipeline({'audio': stream})

```

**Comment by hbredin** [comment] 2022-04-21 06:50
Looks like you are using the old version of pyannote.audio (version `1.x`, from `master` branch).

What you suggest is already implemented in `develop` branch which will soon become pyannote.audio 2.0:

https://github.com/pyannote/pyannote-audio/blob/b577aed28b108dbd8b2eaee679427c54b2a5bf36/pyannote/audio/core/io.py#L387-L388

**Comment by hbredin** [comment] 2022-05-09 14:40
Closing. Please re-open if I am wrong in thinking this issue is now fixed.

**Closed by hbredin** 2022-05-09 14:40 UTC

**Comment by IvanLjubicic** [comment] 2022-08-17 07:14
Hi guys,

is this feature working?

Cause I am getting this error

`  File "/Users/tech/miniconda3/envs/test-app/lib/python3.8/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening <_io.BytesIO object at 0x7f9551cd3400>: Format not recognised.`

Thanks.

**Comment by hbredin** [comment] 2022-08-17 07:52
Would you mind sharing a link to a Google Colab containing a minimum reproducible example that I can quickly run to reproduce the error?

**Comment by IvanLjubicic** [comment] 2022-08-18 18:48
@hbredin thanks for the really fast response, I appreciate it!

I am not sure if that is really completely reproducible via Google Colab because I am actually reading a file from AWS S3 bucket, saving it in a BytesIO object and then trying to call a method for diarization.

Don't know if anyone was experimenting with AWS S3 and this whole process.

`wav_url = create_presigned_url(s3_client=s3_client_enter, bucket_name=bucket_enter,
                                   object_name=file_path,
                                   expiration=3600)

    logger.info("wav_url " + wav_url)

    file_wav = io.BytesIO()

    with urllib2.urlopen(wav_url) as r:
        r.seek = lambda *args: None 
        pdb.from_file(r).export(file_wav, "wav")

    #s3_resource_enter.Object(bucket_enter, file_path).download_fileobj(file_wav)
    file_wav.seek(0)

    diarization = pipeline(file_wav)

**Comment by hbredin** [comment] 2022-08-19 08:30
Without a fully functional minimum reproducible example, I am not able to help, sorry.

**Comment by IvanLjubicic** [comment] 2022-08-21 17:07
@hbredin thanks.

I managed to create Google Collab to reproduce this error. With this file

https://drive.google.com/file/d/1-gJQDYRllwyHFxRg_rCeBYPZYSxZvaK1/view

and this code snippet

https://colab.research.google.com/drive/101zpIF5aey000mK3SUag1xR_CgmBX-aM?usp=sharing

**Comment by hbredin** [comment] 2022-08-26 07:52
The second cell of this colab returns:

```
MessageError: TypeError: google.colab._files is undefined
```

**Comment by hbredin** [comment] 2022-08-26 08:03
The following works but I suspect this is not what you are looking for, are you?

```python
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/voice-activity-detection")
with open("audio.wav", "rb") as fp:
    vad = pipeline(fp)
```

**Comment by IvanLjubicic** [comment] 2022-08-28 08:56
Yes, this works with BytesIO. But changing to speaker-diarization not unfortunately

`pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")
#pipeline = Pipeline.from_pretrained("pyannote/voice-activity-detection")`

**Comment by hbredin** [comment] 2022-08-29 06:45
Ah! It probably fails because the `pyanote/speaker-diarization` file goes through the file multiple times.

You could load the whole file first and then pass it the pipeline like this:

```python
from pyannote.audio import Audio, Pipeline

audio = Audio()
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")

with open("audio.wav", "rb") as fp:
    waveform, sample_rate = audio(fp)

diarization = pipeline({"waveform": waveform, "sample_rate": sample_rate})
```

**Comment by IvanLjubicic** [comment] 2022-08-29 14:57
it works! here is the final solution for this.

```python
    with urllib2.urlopen(wav_url) as r:
        contents = r.read()
        contents_bytesio = io.BytesIO(contents)
        contents_bytesio.seek(0)
        waveform, sample_rate = audio(contents_bytesio)
        diarization = pipeline({"waveform": waveform, "sample_rate": sample_rate})
```

@hbredin thanks! do you maybe have some suggestions on how to speed up the process? because processing one wav file with about a one-minute speech takes about 5.5 minutes to process

**Comment by hbredin** [comment] 2022-08-29 15:00
Yes, I do have a few suggestions but you should probably open a dedicated issue/discussion (or read existing ones because I think I remember the speed issue has come up a few times).
