### ISSUE TITLE
Question about speaker diarization pipeline

### ISSUE THREAD

**Issue by kam1107** [pyannote/pyannote-audio#105] opened 2018-07-12 15:49 UTC
Hi, I tried to follow the tutorial of speaker diarization on AMI dataset. I have gone through the other tutorials and the results applied were stored in tutorials/pipeline/sad etc. However, when I try pyannote-pipeline train --forever ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset it gave the error:
**File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/bin/pyannote-pipeline", line 11, in <module>
    sys.exit(main())
  File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/pipeline.py", line 260, in main
    application.train(protocol_name, subset=subset, n_calls=trials)
  File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/pipeline.py", line 167, in train
    for s, status in enumerate(iterations):
  File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/pipeline/base.py", line 236, in tune_iter
    protocol, subset=subset, learning=True)
  File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/pipeline/base.py", line 98, in objective
    hypothesis = self.apply(current_file)
  File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/pipeline/speaker_diarization.py", line 232, in apply
    speech_turns = super().apply(current_file)
  File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/pipeline/speaker_diarization.py", line 90, in apply
    soft_sad = self.sad_(current_file)
  File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/features/utils.py", line 279, in __call__
    data = np.load(path, mmap_mode='r')
  File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/lib/python3.6/site-packages/numpy/lib/npyio.py", line 418, in load
    return format.open_memmap(file, mode=mmap_mode)
  File "/data/greyostrich/aims/aimsre/xxlu/packages/miniconda3/envs/pyannote/lib/python3.6/site-packages/numpy/lib/format.py", line 747, in open_memmap
    raise ValueError("Filename must be a string.  Memmap cannot use"
ValueError: Filename must be a string.  Memmap cannot use existing file handles.**
I am not sure what caused this error. Could you please help with this?

Many thanks,
Kam

**Comment by hbredin** [comment] 2018-07-16 13:00
I cannot reproduce this error.

**Comment by hbredin** [comment] 2018-07-18 15:00
Yes. `/path/to/scd` should be replaced by `/absolute/path/to/tutorials/pipeline/scd`.

**Comment by hbredin** [comment] 2018-07-19 14:53
This should be fixed in latest release (1.0.1).

**Closed** 2018-07-19 14:53 UTC
Labels: cannot_reproduce
