### ISSUE TITLE
Floating point exception when changing feature step size

### ISSUE THREAD

**Issue by Rachine** [pyannote/pyannote-audio#228] opened 2019-10-30 13:26 UTC
Hi,
I am launching experiments on the DIHARD dataset and I wanted to modify the step size for the computations of the features. 

However, when I am reducing the step size under 0.008 ms (included) it is crashing with an error:
`Exception Floating point`

We tried on several machines, to reproduce the error, it just required to change the line 

https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/models/speech_activity_detection/config.yml#L25 

We tried to decrease the batch size too. 
It is still working if we increase the step size. 

Do you know have any ideas where we should investigate? 

Thank you very much.

**Comment by MarvinLvn** [comment] 2019-10-30 14:12
In **features/base.py**, when executing l220/221 :

```
(start, end), = shifted_frames.crop(segment, mode=mode, fixed=fixed,
                                            return_ranges=True)
```

The crop function returns a negative start due to floating point imprecision.

As a workaround, you can add the following lines  straight after the call to shifted_frames.crop : 

```

**Comment by hbredin** [comment] 2019-11-06 10:56
@MarvinLvn Though this hack fixes (does it?) the issue, I would still like to understand which line raises the `Exception Floating point` error and why this happens.

@Rachine Did you manage to pinpoint it?

**Comment by MarvinLvn** [comment] 2019-11-26 11:10
@hbredin 

That's a though one. I can reproduce the error, but here's what I get from my bash : 

```
Training set: 1it [00:00,  7.05it/s]
Training set: 1it [00:00,  6.23it/s]
                                                                                Floating point exception (core dumped)
```

That's a "Deal with it!" error ... Do you have any insights of how to better localize the error ?

@Rachine Can you confirm that your problem has been solved by the hack ?

**Comment by hbredin** [comment] 2020-01-21 15:00
Closing because @MarvinLvn has been integrated. See 1b0682d.
Please re-open if needed.

**Closed by hbredin** 2020-01-21 15:00 UTC

**Comment by Rachine** [comment] 2020-01-21 17:04
Thank you! Sorry I forgot to anser :/
