### ISSUE TITLE
Manual audio loading before running a Pipeline

### ISSUE THREAD

**Issue by vadimkantorov** [pyannote/pyannote-audio#456] opened 2020-10-06 11:24 UTC
I'm loading a diarization pipeline from [torch.hub](https://github.com/pyannote/pyannote-audio-hub), and calling it like `pipeline(dict(audio = '/path/to/my.wav'))`.

Is it possible to do manual audio loading and still using the pipeline? I have my own audio-loading logic that I'd like to preserve.

Thank you!

**Comment by hbredin** [comment] 2020-10-06 12:40
Closing as duplicate of #431.

Please ask me to re-open if needed.

**Closed by hbredin** 2020-10-06 12:40 UTC

**Comment by vadimkantorov** [comment] 2020-10-06 12:51
Should it be -1.0/1.0 float format? or signed short? are both supported? Should this be added as an example along with loading from path?

**Comment by hbredin** [comment] 2020-10-06 13:14
I think it should be the same as the output of calling `read_audio`:

https://github.com/pyannote/pyannote-audio/blob/b8d623596e1c01a1049a0ba2eb5be2f6bf8ba1a0/pyannote/audio/features/utils.py#L81-L130

**Comment by vadimkantorov** [comment] 2020-10-06 14:12
Should `sample_rate` extra key in the dict work?

**Comment by hbredin** [comment] 2020-10-07 07:23
I don't think so. Just make sure `waveform` is already 16khz.
